### ISSUE TITLE
非常赞的博客主题，但似乎博客评论区的 github 登录挂了

### ISSUE THREAD

**Issue by imageslr** [Renovamen/jekyll-theme-gungnir#1]

**Comment by Renovamen** [comment]
的确挂了...

我搜了一下，好像是因为 gitalk 之前用了 [cors-anywhere](https://github.com/Rob--W/cors-anywhere) 的演示服务器，现在 cors-anywhere 的演示服务器不让用了（[cors-anywhere#301](https://github.com/Rob--W/cors-anywhere/issues/301)）。最新版 gitalk 换了别的服务，我等会升级一下。

多谢提醒。

**Comment by Renovamen** [comment]
已经更新了 gitalk（[a58d2da](https://github.com/Renovamen/jekyll-theme-gungnir/commit/a58d2da9ee93605c21a5588722632b2553ba63bf)），现在应该可以登录了。
